apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: related-work-backups-pvc
spec:
  storageClassName: shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
